accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from accounts.views import reg

urlpatterns = [
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", reg, name="signup"),
]

expenses/expenses/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

expenses/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("receipts/", include("receipts.urls")),
    path("", RedirectView.as_view(url=reverse_lazy("home"))),
    path("accounts/", include("accounts.urls")),
]

receipts/urls.py
from django.urls import path

from receipts.views import (
    ReceiptListView,
    ReceiptCreateView,
    AccountListView,
    ExpenseCategoryListView,
    ExpenseCategoryCreateView,
    AccountCreateView,
)


urlpatterns = [
    path("", ReceiptListView.as_view(), name="home"),
    path("create/", ReceiptCreateView.as_view(), name="create_receipt"),
    path("accounts/", AccountListView.as_view(), name="list_account"),
    path(
        "accounts/create/", AccountCreateView.as_view(), name="create_account"
    ),
    path(
        "categories/create/",
        ExpenseCategoryCreateView.as_view(),
        name="create_category",
    ),
    path(
        "categories/",
        ExpenseCategoryListView.as_view(),
        name="categories_list",
    ),
]

accounts/models.py
from django.db import models

# Create your models here.

receipts/models.py
from django.db import models
from django.conf import settings

# Create your models here.
USER_MODEL = settings.AUTH_USER_MODEL


class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(
        USER_MODEL, related_name="categories", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name


class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(
        USER_MODEL, related_name="accounts", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name


class Receipt(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(decimal_places=3, max_digits=10)
    tax = models.DecimalField(decimal_places=3, max_digits=10)
    date = models.DateTimeField()
    purchaser = models.ForeignKey(
        USER_MODEL, related_name="receipts", on_delete=models.CASCADE
    )
    category = models.ForeignKey(
        "ExpenseCategory", related_name="receipts", on_delete=models.CASCADE
    )
    account = models.ForeignKey(
        "Account", related_name="receipts", on_delete=models.CASCADE, null=True
    )

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate

# Create your views here.


def reg(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password1"]
            user = User.objects.create_user(
                username=username, password=password
            )
            user.save()
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm
    context = {"form": form}
    return render(request, "registration/signup.html", context)

receipts/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from receipts.models import Account, Receipt, ExpenseCategory, Account
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy

# Create your views here.


class ReceiptListView(LoginRequiredMixin, ListView):
    model = Receipt
    template_name = "receipts/list.html"

    def get_queryset(self):
        return Receipt.objects.filter(purchaser=self.request.user)


class ReceiptCreateView(LoginRequiredMixin, CreateView):
    model = Receipt
    template_name = "receipts/edit.html"
    fields = ["vendor", "total", "tax", "date", "category", "account"]

    def get_success_url(self):
        return reverse_lazy("home")

    def form_valid(self, form):
        form.instance.purchaser = self.request.user
        return super().form_valid(form)


class ExpenseCategoryListView(LoginRequiredMixin, ListView):
    model = ExpenseCategory
    template_name = "receipts/categories.html"

    def get_queryset(self):
        return ExpenseCategory.objects.filter(owner=self.request.user)


class AccountListView(LoginRequiredMixin, ListView):
    model = Account
    template_name = "receipts/accounts.html"

    def get_queryset(self):
        return Account.objects.filter(owner=self.request.user)


class ExpenseCategoryCreateView(LoginRequiredMixin, CreateView):
    model = ExpenseCategory
    fields = ["name"]
    template_name = "categories/create.html"

    def get_success_url(self):
        return reverse_lazy("categories_list")

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class AccountCreateView(LoginRequiredMixin, CreateView):
    model = Account
    template_name = "accounts/create.html"
    fields = ["name", "number"]

    success_url = reverse_lazy("list_account")

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

receipts/templates/accounts/create.html
{% extends 'base.html' %}

{% block content %}
<main>
    <div>
        <h1>Create Account</h1>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create</button>
        </form>
    </div>
</main>

{% endblock content %}

receipts/templates/base.html
<!doctype html>
<html lang="en">

<head>
    <title></title>
</head>

<body>
    <header>
        <nav>
            <ul>
                <li>
                    <a href="{% url 'home' %}">Home</a>
                </li>
                <li>
                    <a href="{% url 'create_receipt' %}">Create Receipt</a>
                </li>
                <li>
                    <a href="{% url 'list_account' %}">Your Accounts</a>
                </li>
                <li>
                    <a href="{% url 'create_account' %}">Open a New Account</a>
                </li>
                <li>
                    <a href="{% url 'create_category' %}">Create a New Category</a>
                </li>
                <li>
                    <a href="{% url 'categories_list' %}">Your Category Breakdown</a>
                </li>
                {% if user.is_authenticated %}
                <li><a href="{% url 'logout' %}">Logout</a></li>
                {% else %}
                <li><a href="{% url 'login' %}">Login</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>
    {% block content %}
    {% endblock content %}
</body>


</html>

receipts/templates/categories/create.html
{% extends 'base.html' %}

{% block content %}
<main>
    <div>
        <h1>Create Category</h1>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create</button>
        </form>
    </div>
</main>

{% endblock content %}

receipts/templates/receipts/accounts.html
{% extends 'base.html' %}

{% block content %}

<main>
    <div>
        <h1>My Accounts</h1>
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Number</th>
                    <th>Number of receipts</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    {% for account in account_list %}
                    <td>
                        {{account.name}}
                    </td>
                    <td>
                        {{account.number}}
                    </td>
                    <td>{{account.receipts.all|length}}</td>
                    {% endfor %}
                </tr>
            </tbody>
        </table>
    </div>
</main>


{% endblock content %}

receipts/templates/receipts/categories.html
{% extends 'base.html' %}

{% block content %}
<main>
    <div>
        <h1>Categories</h1>
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Number of receipts</th>
                </tr>
                {% for category in expensecategory_list %}
                <tr>
                    <td>{{category.name}}</td>
                    <td>{{category.receipts.all|length}}</td>
                </tr>
                {% endfor %}
            </thead>
        </table>
    </div>
</main>
{% endblock content %}

receipts/templates/receipts/edit.html
{% extends 'base.html' %}
{% block content %}
<main>
    <div>
        <h1>Create Receipt</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create</button>
        </form>
    </div>
</main>

{% endblock content %}

receipts/templates/receipts/list.html
{% extends 'base.html' %}
{% block content %}
<main>
    <h1>My Receipts</h1>
    <p><a href="{% url 'create_category' %}">Create Category</a></p>
    <p><a href="{% url 'create_account' %}">Create Account</a></p>
    <table>
        <thead>
            <tr>
                <th>Vendor</th>
                <th>Total</th>
                <th>Tax</th>
                <th>Due Date</th>
                <th>Category</th>
                <th>Account</th>
            </tr>
        </thead>
        <tbody>
            {% for receipt in receipt_list %}
            <tr>

                <td>
                    {{receipt.vendor}}
                </td>
                <td>
                    {{receipt.total}}
                </td>
                <td>
                    {{receipt.tax}}
                </td>
                <td>
                    {{receipt.due_date | date:"j/n/y"}}
                </td>
                <td>
                    {{receipt.category}}
                </td>
                <td>
                    {{receipt.account}}
                </td>
            </tr>
            {% endfor receipt_list %}
        </tbody>
    </table>
</main>
{% endblock content %}